<a href="https://colab.research.google.com/github/Abdulmajeed-A/Tuwaiq-Linear-Algebra/blob/main/project_linear_algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1: Import Libraries

In [21]:
# Nawaf
import pandas as pd

# Step 2: Load Data

In [22]:
# Mohammed
import kagglehub

# Download latest version
path = kagglehub.dataset_download("yashdev01/spotify-tracks-dataset")

print("Path to dataset files:", path)
df = pd.read_csv(path + "/spotify-tracks-dataset.csv")

Using Colab cache for faster access to the 'spotify-tracks-dataset' dataset.
Path to dataset files: /kaggle/input/spotify-tracks-dataset

In [23]:
df

,Unnamed: 0.1,Unnamed: 0,track_id,artists,album_name,track_name,popularity,duration_ms,explicit,danceability,...,loudness,mode,speechiness,acousticness,instrumentalness,liveness,valence,tempo,time_signature,track_genre
0,0,0,5SuOikwiRyPMVoIQDJUgSV,Gen Hoshino,Comedy,Comedy,73,230666,False,0.676,...,-6.746,0,0.1430,0.0322,0.000001,0.3580,0.7150,87.917,4,acoustic
1,1,1,4qPNDBW1i3p13qLCt0Ki3A,Ben Woodward,Ghost (Acoustic),Ghost - Acoustic,55,149610,False,0.420,...,-17.235,1,0.0763,0.9240,0.000006,0.1010,0.2670,77.489,4,acoustic
2,2,2,1iJBSr7s7jYXzM8EGcbK5b,Ingrid Michaelson;ZAYN,To Begin Again,To Begin Again,57,210826,False,0.438,...,-9.734,1,0.0557,0.2100,0.000000,0.1170,0.1200,76.332,4,acoustic
3,3,3,6lfxq3CG4xtTiEg7opyCyx,Kina Grannis,Crazy Rich Asians (Original Motion Picture Sou...,Can't Help Falling In Love,71,201933,False,0.266,...,-18.515,1,0.0363,0.9050,0.000071,0.1320,0.1430,181.740,3,acoustic
4,4,4,5vjLSffimiIP26QG5WcN2K,Chord Overstreet,Hold On,Hold On,82,198853,False,0.618,...,-9.681,1,0.0526,0.4690,0.000000,0.0829,0.1670,119.949,4,acoustic
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113995,113995,113995,2C3TZjDRiAzdyViavDJ217,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Sleep My Little Boy,21,384999,False,0.172,...,-16.393,1,0.0422,0.6400,0.928000,0.0863,0.0339,125.995,5,world-music
113996,113996,113996,1hIz5L4IB9hN3WRYPOCGPw,Rainy Lullaby,#mindfulness - Soft Rain for Mindful Meditatio...,Water Into Light,22,385000,False,0.174,...,-18.318,0,0.0401,0.9940,0.976000,0.1050,0.0350,85.239,4,world-music
113997,113997,113997,6x8ZfSoqDjuNa5SVP5QjvX,Cesária Evora,Best Of,Miss Perfumado,22,271466,False,0.629,...,-10.895,0,0.0420,0.8670,0.000000,0.0839,0.7430,132.378,4,world-music
113998,113998,113998,2e6sXL2bYv4bSz6VTdnfLs,Michael W. Smith,Change Your World,Friends,41,283893,False,0.587,...,-10.889,1,0.0297,0.3810,0.000000,0.2700,0.4130,135.960,4,world-music
113999,113999,113999,2hETkH7cOfqmz3LqZDHZf5,Cesária Evora,Miss Perfumado,Barbincor,22,241826,False,0.526,...,-10.204,0,0.0725,0.6810,0.000000,0.0893,0.7080,79.198,4,world-music

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.isnull().sum()

Unnamed: 0.1        0
Unnamed: 0          0
track_id            0
artists             1
album_name          1
track_name          1
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

In [26]:
df.dropna(inplace=True)

In [27]:
df.isnull().sum()

Unnamed: 0.1        0
Unnamed: 0          0
track_id            0
artists             0
album_name          0
track_name          0
popularity          0
duration_ms         0
explicit            0
danceability        0
energy              0
key                 0
loudness            0
mode                0
speechiness         0
acousticness        0
instrumentalness    0
liveness            0
valence             0
tempo               0
time_signature      0
track_genre         0
dtype: int64

# Step 3: Mathematical Focus

AX = λX:

In [28]:
# Mohammed
import sympy as sp

a, b, c, d = sp.symbols('a b c d')
A = sp.Matrix([[a, b],
               [c, d]])
λ = sp.symbols('λ')
x1, x2 = sp.symbols('x1 x2')
X = sp.Matrix([[x1],
               [x2]])
eq = sp.Eq(A@X, λ*X)
print("AX = λX:")
sp.pprint(eq)

AX = λX:
⎡a⋅x₁ + b⋅x₂⎤   ⎡x₁⋅λ⎤
⎢           ⎥ = ⎢    ⎥
⎣c⋅x₁ + d⋅x₂⎦   ⎣x₂⋅λ⎦



```
```

Characteristic equation:

In [29]:
# Mohammed
I = sp.eye(2)
char_eq = A - λ*I
char_eq_det = sp.det(char_eq)
print("\nCharacteristic equation:")
sp.pprint(sp.Eq(char_eq_det, 0))
print('-'*100)


#
A = sp.Matrix([[2, 1],
               [1, 2]])


λ = sp.symbols('λ')
x1, x2 = sp.symbols('x1 x2')
X = sp.Matrix([[x1],
               [x2]])


eq = sp.Eq(A*X, λ*X)
print("AX = λX:")
sp.pprint(eq)


I = sp.eye(2)             #
char_eq = A - λ*I
char_eq_det = sp.det(char_eq)
print("\nCharacteristic equation:")
sp.pprint(sp.Eq(char_eq_det, 0))


eigenvals = sp.solve(char_eq_det, λ)
print("\nEigenvalues (λ):", eigenvals)


for val in eigenvals:
    vecs = (A - val*I).nullspace()
    print(f"\nEigenvector(s) for λ = {val}:")
    sp.pprint(vecs[0])

Characteristic equation:
                         2
a⋅d - a⋅λ - b⋅c - d⋅λ + λ  = 0
----------------------------------------------------------------------------------------------------
AX = λX:
⎡2⋅x₁ + x₂⎤   ⎡x₁⋅λ⎤
⎢         ⎥ = ⎢    ⎥
⎣x₁ + 2⋅x₂⎦   ⎣x₂⋅λ⎦

Characteristic equation:
 2
λ  - 4⋅λ + 3 = 0

Eigenvalues (λ): [1, 3]

Eigenvector(s) for λ = 1:
⎡-1⎤
⎢  ⎥
⎣1 ⎦

Eigenvector(s) for λ = 3:
⎡1⎤
⎢ ⎥
⎣1⎦

Eigenvalue interpretation:

In [30]:
# Saad
import numpy as np
from sklearn.preprocessing import StandardScaler

# Load dataset
df = pd.read_csv(path + "/spotify-tracks-dataset.csv")

# 1: Select chosen features only
features = ['danceability','energy','loudness','speechiness',
            'acousticness','instrumentalness','liveness',
            'valence','tempo','duration_ms']

X = df[features]

# Remove missing values
X = X.dropna()

print("Shape of selected features:", X.shape)
# 2️: Standardize features (mean=0, std=1)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Mean after scaling (should be 0):")
print(np.mean(X_scaled, axis=0))

print("\nStd after scaling (should be 1):")
print(np.std(X_scaled, axis=0))

# 3️: Covariance Matrix
cov_matrix = np.cov(X_scaled.T)

print("Covariance Matrix shape:", cov_matrix.shape)
print("\nCovariance Matrix:\n", cov_matrix)

# 4️: Eigenvalues & Eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(cov_matrix)

print("Eigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Shape of selected features: (114000, 10)
Mean after scaling (should be 0):
[-8.87555137e-16  2.33357193e-16 -1.45598933e-16 -1.31637391e-16
  2.63274782e-16  1.99450592e-18 -2.14908013e-16 -5.58461659e-17
 -2.79230829e-17  2.39340711e-17]

Std after scaling (should be 1):
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
Covariance Matrix shape: (10, 10)

Covariance Matrix:
 [[ 1.00000877e+00  1.34326662e-01  2.59079006e-01  1.08627043e-01
  -1.71534836e-01 -1.85607878e-01 -1.31618011e-01  4.77345423e-01
  -5.04503140e-02 -7.34268846e-02]
 [ 1.34326662e-01  1.00000877e+00  7.61696641e-01  1.42510118e-01
  -7.33912759e-01 -1.81880807e-01  1.84797143e-01  2.58936267e-01
   2.47852684e-01  5.85232914e-02]
 [ 2.59079006e-01  7.61696641e-01  1.00000877e+00  6.08268617e-02
  -5.89807841e-01 -4.33480664e-01  7.68993366e-02  2.79850337e-01
   2.12447760e-01 -3.47019561e-03]
 [ 1.08627043e-01  1.42510118e-01  6.08268617e-02  1.00000877e+00
  -2.18635497e-03 -8.96165509e-02  2.05220858e-01  3.66349042e-02
   1.72733749e-02 -6.26003826e-02]
 [-1.71534836e-01 -7.33912759e-01 -5.89807841e-01 -2.18635497e-03
   1.00000877e+00  1.04028032e-01 -2.07005424e-02 -1.07071119e-01
  -2.08225974e-01 -1.03789040e-01]
 [-1.85607878e-01 -1.81880807e-01 -4.33480664e-01 -8.96165509e-02
   1.04028032e-01  1.00000877e+00 -7.98932831e-02 -3.24315173e-01
  -5.03308428e-02  1.24371593e-01]
 [-1.31618011e-01  1.84797143e-01  7.68993366e-02  2.05220858e-01
  -2.07005424e-02 -7.98932831e-02  1.00000877e+00  1.90864222e-02
   5.99772572e-04  1.03214192e-02]
 [ 4.77345423e-01  2.58936267e-01  2.79850337e-01  3.66349042e-02
  -1.07071119e-01 -3.24315173e-01  1.90864222e-02  1.00000877e+00
   7.82737543e-02 -1.54479967e-01]
 [-5.04503140e-02  2.47852684e-01  2.12447760e-01  1.72733749e-02
  -2.08225974e-01 -5.03308428e-02  5.99772572e-04  7.82737543e-02
   1.00000877e+00  2.43458193e-02]
 [-7.34268846e-02  5.85232914e-02 -3.47019561e-03 -6.26003826e-02
  -1.03789040e-01  1.24371593e-01  1.03214192e-02 -1.54479967e-01
   2.43458193e-02  1.00000877e+00]]
Eigenvalues:
 [2.87391764 1.52397855 0.14006853 1.23403171 0.32541349 0.46316757
 0.97111027 0.74795291 0.88683166 0.83361539]

Eigenvectors:
 [[ 0.24693473  0.48365776  0.1563146  -0.21695211 -0.06262614 -0.62026172
   0.38918882 -0.13807611 -0.27103804  0.03089868]
 [ 0.50844047 -0.26331494  0.73373887  0.0373302  -0.17875831  0.22973457
   0.05470133 -0.09092327  0.00532382 -0.1907017 ]
 [ 0.51675806 -0.07783604 -0.51675705 -0.03915353 -0.62197488 -0.05323496
  -0.03747389  0.16645932  0.18339619 -0.07679797]
 [ 0.10113568  0.09131167 -0.10064567  0.60910946  0.04424819  0.17829621
   0.25679353  0.41784621 -0.56343766 -0.09242329]
 [-0.43828184  0.31550889  0.30241116  0.17657461 -0.69040063  0.08640025
  -0.11447244  0.03674576  0.00912577  0.2950874 ]
 [-0.28342914 -0.32124647 -0.18683627 -0.15350619 -0.29004623  0.11928442
   0.23235608 -0.5337415  -0.45518555 -0.33701317]
 [ 0.08500415 -0.14397266 -0.06970379  0.69581662  0.03571357 -0.29382086
   0.05695658 -0.53673536  0.2638897   0.18561775]
 [ 0.29631839  0.48767471 -0.16919875 -0.07256618  0.11340602  0.61065892
   0.01240636 -0.41484177 -0.06184962  0.28042198]
 [ 0.18865278 -0.24028867  0.00546319 -0.06890366  0.00845291 -0.19711697
  -0.61036753 -0.06677259 -0.54189225  0.43853513]
 [-0.01417736 -0.40411086 -0.01219168 -0.17341808 -0.01803051  0.08994459
   0.57892386  0.13962959  0.03203683  0.66496632]]

Diagonalization:

In [36]:
# Saad
# 4️: Diagonalization

# Matrix P (eigenvectors)
P = eigenvectors

# Diagonal matrix D (eigenvalues)
D = np.diag(eigenvalues)

# Compute P inverse
P_inv = np.linalg.inv(P)

# Reconstruct covariance matrix
C_reconstructed = P @ D @ P_inv

print("Original Covariance Matrix:\n", cov_matrix)
print("\nReconstructed Covariance Matrix (PDP⁻¹):\n", C_reconstructed)

# Check if they are approximately equal
print("\nAre they equal?")
print(np.allclose(cov_matrix, C_reconstructed))

Original Covariance Matrix:
 [[ 1.00000877e+00  1.34326662e-01  2.59079006e-01  1.08627043e-01
  -1.71534836e-01 -1.85607878e-01 -1.31618011e-01  4.77345423e-01
  -5.04503140e-02 -7.34268846e-02]
 [ 1.34326662e-01  1.00000877e+00  7.61696641e-01  1.42510118e-01
  -7.33912759e-01 -1.81880807e-01  1.84797143e-01  2.58936267e-01
   2.47852684e-01  5.85232914e-02]
 [ 2.59079006e-01  7.61696641e-01  1.00000877e+00  6.08268617e-02
  -5.89807841e-01 -4.33480664e-01  7.68993366e-02  2.79850337e-01
   2.12447760e-01 -3.47019561e-03]
 [ 1.08627043e-01  1.42510118e-01  6.08268617e-02  1.00000877e+00
  -2.18635497e-03 -8.96165509e-02  2.05220858e-01  3.66349042e-02
   1.72733749e-02 -6.26003826e-02]
 [-1.71534836e-01 -7.33912759e-01 -5.89807841e-01 -2.18635497e-03
   1.00000877e+00  1.04028032e-01 -2.07005424e-02 -1.07071119e-01
  -2.08225974e-01 -1.03789040e-01]
 [-1.85607878e-01 -1.81880807e-01 -4.33480664e-01 -8.96165509e-02
   1.04028032e-01  1.00000877e+00 -7.98932831e-02 -3.24315173e-01
  -5.03308428e-02  1.24371593e-01]
 [-1.31618011e-01  1.84797143e-01  7.68993366e-02  2.05220858e-01
  -2.07005424e-02 -7.98932831e-02  1.00000877e+00  1.90864222e-02
   5.99772572e-04  1.03214192e-02]
 [ 4.77345423e-01  2.58936267e-01  2.79850337e-01  3.66349042e-02
  -1.07071119e-01 -3.24315173e-01  1.90864222e-02  1.00000877e+00
   7.82737543e-02 -1.54479967e-01]
 [-5.04503140e-02  2.47852684e-01  2.12447760e-01  1.72733749e-02
  -2.08225974e-01 -5.03308428e-02  5.99772572e-04  7.82737543e-02
   1.00000877e+00  2.43458193e-02]
 [-7.34268846e-02  5.85232914e-02 -3.47019561e-03 -6.26003826e-02
  -1.03789040e-01  1.24371593e-01  1.03214192e-02 -1.54479967e-01
   2.43458193e-02  1.00000877e+00]]

Reconstructed Covariance Matrix (PDP⁻¹):
 [[ 1.00000877e+00  1.34326662e-01  2.59079006e-01  1.08627043e-01
  -1.71534836e-01 -1.85607878e-01 -1.31618011e-01  4.77345423e-01
  -5.04503140e-02 -7.34268846e-02]
 [ 1.34326662e-01  1.00000877e+00  7.61696641e-01  1.42510118e-01
  -7.33912759e-01 -1.81880807e-01  1.84797143e-01  2.58936267e-01
   2.47852684e-01  5.85232914e-02]
 [ 2.59079006e-01  7.61696641e-01  1.00000877e+00  6.08268617e-02
  -5.89807841e-01 -4.33480664e-01  7.68993366e-02  2.79850337e-01
   2.12447760e-01 -3.47019561e-03]
 [ 1.08627043e-01  1.42510118e-01  6.08268617e-02  1.00000877e+00
  -2.18635497e-03 -8.96165509e-02  2.05220858e-01  3.66349042e-02
   1.72733749e-02 -6.26003826e-02]
 [-1.71534836e-01 -7.33912759e-01 -5.89807841e-01 -2.18635497e-03
   1.00000877e+00  1.04028032e-01 -2.07005424e-02 -1.07071119e-01
  -2.08225974e-01 -1.03789040e-01]
 [-1.85607878e-01 -1.81880807e-01 -4.33480664e-01 -8.96165509e-02
   1.04028032e-01  1.00000877e+00 -7.98932831e-02 -3.24315173e-01
  -5.03308428e-02  1.24371593e-01]
 [-1.31618011e-01  1.84797143e-01  7.68993366e-02  2.05220858e-01
  -2.07005424e-02 -7.98932831e-02  1.00000877e+00  1.90864222e-02
   5.99772572e-04  1.03214192e-02]
 [ 4.77345423e-01  2.58936267e-01  2.79850337e-01  3.66349042e-02
  -1.07071119e-01 -3.24315173e-01  1.90864222e-02  1.00000877e+00
   7.82737543e-02 -1.54479967e-01]
 [-5.04503140e-02  2.47852684e-01  2.12447760e-01  1.72733749e-02
  -2.08225974e-01 -5.03308428e-02  5.99772572e-04  7.82737543e-02
   1.00000877e+00  2.43458193e-02]
 [-7.34268846e-02  5.85232914e-02 -3.47019561e-03 -6.26003826e-02
  -1.03789040e-01  1.24371593e-01  1.03214192e-02 -1.54479967e-01
   2.43458193e-02  1.00000877e+00]]

Are they equal?
True

# Step 4: AI Connection

Principal Component Analysis (PCA):

In [32]:
# Nawaf

Principal directions:

In [33]:
# Abdulmajeed

Variance explanation:

In [34]:
# Abdulmajeed

# Step 5: Visualization

In [35]:
# Abdullah